import {
  GameItem,
  ProductItem,
  JokiTierItem,
  JokiWorkerItem,
  OrderTopupItem,
  OrderJokiItem,
  VoucherItem,
  AuditLogItem,
} from "./types";

export const DUMMY_GAMES: GameItem[] = [
  {
    id: "g-mlbb",
    slug: "mobile-legends",
    name: "Mobile Legends: Bang Bang",
    publisher: "Moonton",
    category: "MOBA",
    platform: "Mobile",
    logoUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=500&auto=format&fit=crop&q=60",
    bannerUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop&q=80",
    needsZoneId: true,
    hasJoki: true,
    isActive: true,
    sortOrder: 1,
    popular: true,
  },
  {
    id: "g-ff",
    slug: "free-fire",
    name: "Free Fire",
    publisher: "Garena",
    category: "Battle Royale",
    platform: "Mobile",
    logoUrl: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=500&auto=format&fit=crop&q=60",
    bannerUrl: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&auto=format&fit=crop&q=80",
    needsZoneId: false,
    hasJoki: true,
    isActive: true,
    sortOrder: 2,
    popular: true,
  },
  {
    id: "g-pubgm",
    slug: "pubg-mobile",
    name: "PUBG Mobile",
    publisher: "Level Infinite",
    category: "Battle Royale",
    platform: "Mobile",
    logoUrl: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=500&auto=format&fit=crop&q=60",
    bannerUrl: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&auto=format&fit=crop&q=80",
    needsZoneId: false,
    hasJoki: true,
    isActive: true,
    sortOrder: 3,
    popular: true,
  },
  {
    id: "g-val",
    slug: "valorant",
    name: "Valorant",
    publisher: "Riot Games",
    category: "FPS",
    platform: "PC",
    logoUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=500&auto=format&fit=crop&q=60",
    bannerUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80",
    needsZoneId: false,
    hasJoki: true,
    isActive: true,
    sortOrder: 4,
    popular: true,
  },
  {
    id: "g-genshin",
    slug: "genshin-impact",
    name: "Genshin Impact",
    publisher: "HoYoverse",
    category: "RPG",
    platform: "Semua Platform",
    logoUrl: "https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=500&auto=format&fit=crop&q=60",
    bannerUrl: "https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=1200&auto=format&fit=crop&q=80",
    needsZoneId: true,
    hasJoki: false,
    isActive: true,
    sortOrder: 5,
    popular: true,
  },
  {
    id: "g-hok",
    slug: "honor-of-kings",
    name: "Honor of Kings",
    publisher: "Level Infinite",
    category: "MOBA",
    platform: "Mobile",
    logoUrl: "https://images.unsplash.com/photo-1563089145-599997674d42?w=500&auto=format&fit=crop&q=60",
    bannerUrl: "https://images.unsplash.com/photo-1563089145-599997674d42?w=1200&auto=format&fit=crop&q=80",
    needsZoneId: false,
    hasJoki: true,
    isActive: true,
    sortOrder: 6,
    popular: false,
  },
];

export const DUMMY_PRODUCTS: ProductItem[] = [
  // Mobile Legends
  {
    id: "p-ml-86",
    gameId: "g-mlbb",
    gameSlug: "mobile-legends",
    sku: "ML-86-DM",
    label: "86 Diamonds (78 + 8 Bonus)",
    nominalQty: 86,
    priceCost: 18500,
    priceSell: 22000,
    margin: 3500,
    stock: 540,
    isActive: true,
    isPromo: true,
    discountPercent: 10,
    sortOrder: 1,
  },
  {
    id: "p-ml-172",
    gameId: "g-mlbb",
    gameSlug: "mobile-legends",
    sku: "ML-172-DM",
    label: "172 Diamonds (156 + 16 Bonus)",
    nominalQty: 172,
    priceCost: 36500,
    priceSell: 43000,
    margin: 6500,
    stock: 350,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: "p-ml-257",
    gameId: "g-mlbb",
    gameSlug: "mobile-legends",
    sku: "ML-257-DM",
    label: "257 Diamonds (234 + 23 Bonus)",
    nominalQty: 257,
    priceCost: 55000,
    priceSell: 64500,
    margin: 9500,
    stock: 280,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: "p-ml-706",
    gameId: "g-mlbb",
    gameSlug: "mobile-legends",
    sku: "ML-706-DM",
    label: "706 Diamonds (625 + 81 Bonus)",
    nominalQty: 706,
    priceCost: 152000,
    priceSell: 175000,
    margin: 23000,
    stock: 190,
    isActive: true,
    isPromo: true,
    discountPercent: 12,
    sortOrder: 4,
  },
  {
    id: "p-ml-wp",
    gameId: "g-mlbb",
    gameSlug: "mobile-legends",
    sku: "ML-WEEKLY-PASS",
    label: "Weekly Diamond Pass (WDP)",
    nominalQty: 1,
    priceCost: 26000,
    priceSell: 29500,
    margin: 3500,
    stock: 999,
    isActive: true,
    isPromo: true,
    discountPercent: 15,
    sortOrder: 5,
  },
  {
    id: "p-ml-2195",
    gameId: "g-mlbb",
    gameSlug: "mobile-legends",
    sku: "ML-2195-DM",
    label: "2195 Diamonds (1860 + 335 Bonus)",
    nominalQty: 2195,
    priceCost: 460000,
    priceSell: 520000,
    margin: 60000,
    stock: 80,
    isActive: true,
    sortOrder: 6,
  },

  // Free Fire
  {
    id: "p-ff-140",
    gameId: "g-ff",
    gameSlug: "free-fire",
    sku: "FF-140-DM",
    label: "140 Diamonds",
    nominalQty: 140,
    priceCost: 17000,
    priceSell: 19800,
    margin: 2800,
    stock: 450,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "p-ff-355",
    gameId: "g-ff",
    gameSlug: "free-fire",
    sku: "FF-355-DM",
    label: "355 Diamonds",
    nominalQty: 355,
    priceCost: 43000,
    priceSell: 50000,
    margin: 7000,
    stock: 400,
    isActive: true,
    isPromo: true,
    discountPercent: 8,
    sortOrder: 2,
  },
  {
    id: "p-ff-720",
    gameId: "g-ff",
    gameSlug: "free-fire",
    sku: "FF-720-DM",
    label: "720 Diamonds",
    nominalQty: 720,
    priceCost: 86000,
    priceSell: 99000,
    margin: 13000,
    stock: 310,
    isActive: true,
    sortOrder: 3,
  },

  // Valorant
  {
    id: "p-val-420",
    gameId: "g-val",
    gameSlug: "valorant",
    sku: "VAL-420-VP",
    label: "420 Valorant Points",
    nominalQty: 420,
    priceCost: 38500,
    priceSell: 45000,
    margin: 6500,
    stock: 200,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "p-val-700",
    gameId: "g-val",
    gameSlug: "valorant",
    sku: "VAL-700-VP",
    label: "700 Valorant Points",
    nominalQty: 700,
    priceCost: 65000,
    priceSell: 75000,
    margin: 10000,
    stock: 180,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: "p-val-1375",
    gameId: "g-val",
    gameSlug: "valorant",
    sku: "VAL-1375-VP",
    label: "1.375 Valorant Points",
    nominalQty: 1375,
    priceCost: 125000,
    priceSell: 145000,
    margin: 20000,
    stock: 150,
    isActive: true,
    isPromo: true,
    discountPercent: 5,
    sortOrder: 3,
  },
  {
    id: "p-val-2400",
    gameId: "g-val",
    gameSlug: "valorant",
    sku: "VAL-2400-VP",
    label: "2.400 Valorant Points",
    nominalQty: 2400,
    priceCost: 220000,
    priceSell: 250000,
    margin: 30000,
    stock: 90,
    isActive: true,
    sortOrder: 4,
  },
];

export const DUMMY_JOKI_TIERS: JokiTierItem[] = [
  // Mobile Legends Tiers
  {
    id: "jt-ml-1",
    gameId: "g-mlbb",
    gameSlug: "mobile-legends",
    tierSlug: "grandmaster",
    tierName: "Grandmaster",
    orderIndex: 1,
    pricePerTier: 6000,
    estimatedMinutes: 45,
  },
  {
    id: "jt-ml-2",
    gameId: "g-mlbb",
    gameSlug: "mobile-legends",
    tierSlug: "epic-v-i",
    tierName: "Epic (Per Bintang)",
    orderIndex: 2,
    pricePerTier: 7500,
    estimatedMinutes: 60,
  },
  {
    id: "jt-ml-3",
    gameId: "g-mlbb",
    gameSlug: "mobile-legends",
    tierSlug: "legend-v-i",
    tierName: "Legend (Per Bintang)",
    orderIndex: 3,
    pricePerTier: 10000,
    estimatedMinutes: 75,
  },
  {
    id: "jt-ml-4",
    gameId: "g-mlbb",
    gameSlug: "mobile-legends",
    tierSlug: "mythic-placement",
    tierName: "Mythic Placement (10 Match)",
    orderIndex: 4,
    pricePerTier: 85000,
    estimatedMinutes: 240,
  },
  {
    id: "jt-ml-5",
    gameId: "g-mlbb",
    gameSlug: "mobile-legends",
    tierSlug: "mythic-star",
    tierName: "Mythic Honor (Per Bintang)",
    orderIndex: 5,
    pricePerTier: 14000,
    estimatedMinutes: 90,
  },
  {
    id: "jt-ml-6",
    gameId: "g-mlbb",
    gameSlug: "mobile-legends",
    tierSlug: "mythic-glory",
    tierName: "Mythic Glory 50★+ (Per Bintang)",
    orderIndex: 6,
    pricePerTier: 22000,
    estimatedMinutes: 120,
  },
  {
    id: "jt-ml-7",
    gameId: "g-mlbb",
    gameSlug: "mobile-legends",
    tierSlug: "mythical-immortal",
    tierName: "Mythical Immortal 100★+",
    orderIndex: 7,
    pricePerTier: 35000,
    estimatedMinutes: 150,
  },
];

export const DUMMY_JOKI_WORKERS: JokiWorkerItem[] = [
  {
    id: "w-1",
    userId: "u-joki-1",
    displayName: 'Andika "ViperML"',
    avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=60",
    ratingAvg: 4.95,
    ratingCount: 143,
    skillGames: ["Mobile Legends", "Honor of Kings"],
    isOnline: true,
    commissionPct: 75,
    activeOrders: 2,
  },
  {
    id: "w-2",
    userId: "u-joki-2",
    displayName: 'Sarah "Valkyrie"',
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=60",
    ratingAvg: 4.98,
    ratingCount: 215,
    skillGames: ["Valorant", "PUBG Mobile"],
    isOnline: true,
    commissionPct: 75,
    activeOrders: 1,
  },
  {
    id: "w-3",
    userId: "u-joki-3",
    displayName: 'Kevin "Raptor"',
    avatarUrl: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=60",
    ratingAvg: 4.89,
    ratingCount: 98,
    skillGames: ["Free Fire", "Mobile Legends"],
    isOnline: false,
    commissionPct: 70,
    activeOrders: 0,
  },
];

export const DUMMY_PAYMENT_METHODS = [
  {
    id: "qris",
    code: "XENDIT_QRIS" as const,
    name: "QRIS Realtime",
    category: "Instant QR",
    fee: 1000,
    badge: "Otomatis & Tercepat",
    description: "Bisa bayar dari GoPay, OVO, DANA, BCA Mobile, Livin, dll.",
    popular: true,
  },
  {
    id: "bca-va",
    code: "XENDIT_VA" as const,
    name: "BCA Virtual Account",
    category: "Virtual Account",
    fee: 2500,
    badge: "24 Jam",
    description: "Konfirmasi instan otomatis tanpa perlu upload bukti.",
    popular: true,
  },
  {
    id: "mandiri-va",
    code: "XENDIT_VA" as const,
    name: "Mandiri Virtual Account",
    category: "Virtual Account",
    fee: 2500,
    badge: "24 Jam",
    description: "Bayar via Livin by Mandiri atau ATM.",
  },
  {
    id: "bri-va",
    code: "XENDIT_VA" as const,
    name: "BRI Virtual Account (BRIVA)",
    category: "Virtual Account",
    fee: 2500,
    badge: "24 Jam",
    description: "Bayar via BRImo atau ATM BRI.",
  },
  {
    id: "dana",
    code: "XENDIT_EWALLET" as const,
    name: "DANA",
    category: "E-Wallet",
    fee: 1500,
    badge: "Diskon 5%",
    description: "Terhubung langsung dengan aplikasi DANA Anda.",
    popular: true,
  },
  {
    id: "gopay",
    code: "XENDIT_EWALLET" as const,
    name: "GoPay",
    category: "E-Wallet",
    fee: 1500,
    badge: "Mudah",
    description: "Buka GoPay dan selesaikan pembayaran satu ketuk.",
  },
  {
    id: "manual-bca",
    code: "MANUAL_TRANSFER" as const,
    name: "Transfer Manual BCA",
    category: "Manual Bank",
    fee: 0,
    badge: "Bebas Biaya Admin",
    description: "BCA Rek: 1234567890 a/n PT TopUpGame Indonesia (Upload Bukti).",
  },
];

export const DUMMY_TOPUP_ORDERS: OrderTopupItem[] = [
  {
    id: "ord-1",
    invoiceId: "TUG-2025-000431",
    userId: "u-1",
    userName: "Rizky Aditya Pratama",
    gameId: "g-mlbb",
    gameName: "Mobile Legends",
    gameSlug: "mobile-legends",
    productId: "p-ml-172",
    productLabel: "172 Diamonds (156 + 16 Bonus)",
    gameUserId: "84729104",
    gameZoneId: "2104",
    gameNickname: "RizkySlayer",
    qty: 1,
    subtotal: 43000,
    discount: 5000,
    fee: 1000,
    total: 39000,
    status: "SUCCESS",
    paymentMethod: "XENDIT_QRIS",
    paymentMethodLabel: "QRIS Realtime",
    expiresAt: "2025-05-10T14:30:00Z",
    paidAt: "2025-05-10T14:02:15Z",
    createdAt: "2025-05-10T14:01:00Z",
  },
  {
    id: "ord-2",
    invoiceId: "TUG-2025-000432",
    userId: "u-1",
    userName: "Rizky Aditya Pratama",
    gameId: "g-ff",
    gameName: "Free Fire",
    gameSlug: "free-fire",
    productId: "p-ff-355",
    productLabel: "355 Diamonds",
    gameUserId: "99182341",
    gameNickname: "BooyahKing",
    qty: 1,
    subtotal: 50000,
    discount: 0,
    fee: 2500,
    total: 52500,
    status: "PENDING_PAYMENT",
    paymentMethod: "XENDIT_VA",
    paymentMethodLabel: "BCA Virtual Account",
    expiresAt: "2025-05-10T15:30:00Z",
    createdAt: "2025-05-10T15:00:00Z",
  },
  {
    id: "ord-3",
    invoiceId: "TUG-2025-000430",
    userId: "u-1",
    userName: "Rizky Aditya Pratama",
    gameId: "g-val",
    gameName: "Valorant",
    gameSlug: "valorant",
    productId: "p-val-1375",
    productLabel: "1.375 Valorant Points",
    gameUserId: "ViperAce#ID1",
    qty: 1,
    subtotal: 145000,
    discount: 10000,
    fee: 1500,
    total: 136500,
    status: "PROCESSING",
    paymentMethod: "XENDIT_EWALLET",
    paymentMethodLabel: "DANA",
    expiresAt: "2025-05-10T11:30:00Z",
    paidAt: "2025-05-10T11:05:00Z",
    createdAt: "2025-05-10T11:00:00Z",
  },
  {
    id: "ord-4",
    invoiceId: "TUG-2025-000428",
    userId: "u-2",
    userName: "Dimas Anggara",
    gameId: "g-mlbb",
    gameName: "Mobile Legends",
    gameSlug: "mobile-legends",
    productId: "p-ml-wp",
    productLabel: "Weekly Diamond Pass (WDP)",
    gameUserId: "10293847",
    gameZoneId: "2019",
    gameNickname: "LordDimas",
    qty: 2,
    subtotal: 59000,
    discount: 0,
    fee: 0,
    total: 59000,
    status: "SUCCESS",
    paymentMethod: "MANUAL_TRANSFER",
    paymentMethodLabel: "Transfer Manual BCA",
    expiresAt: "2025-05-09T20:30:00Z",
    paidAt: "2025-05-09T20:15:00Z",
    createdAt: "2025-05-09T20:00:00Z",
  },
  {
    id: "ord-5",
    invoiceId: "TUG-2025-000410",
    userId: "u-3",
    userName: "Budi Santoso",
    gameId: "g-pubgm",
    gameName: "PUBG Mobile",
    gameSlug: "pubg-mobile",
    productId: "p-pubg-660",
    productLabel: "660 UC",
    gameUserId: "5123984712",
    gameNickname: "SniperBudi",
    qty: 1,
    subtotal: 125000,
    discount: 0,
    fee: 1000,
    total: 126000,
    status: "EXPIRED",
    paymentMethod: "XENDIT_QRIS",
    paymentMethodLabel: "QRIS Realtime",
    expiresAt: "2025-05-08T10:30:00Z",
    createdAt: "2025-05-08T10:00:00Z",
  },
];

export const DUMMY_JOKI_ORDERS: OrderJokiItem[] = [
  {
    id: "jki-1",
    invoiceId: "TUG-JKI-2025-000112",
    userId: "u-1",
    userName: "Rizky Aditya Pratama",
    userPhone: "0812-3456-7890",
    gameId: "g-mlbb",
    gameName: "Mobile Legends: Bang Bang",
    workerId: "w-1",
    workerName: 'Andika "ViperML"',
    startTierName: "Legend V (1 Bintang)",
    targetTierName: "Mythic Placement (0 Bintang)",
    currentTierName: "Legend I (4 Bintang)",
    accountEmail: "rizky.mlbb@gmail.com",
    notes: "Tolong fokus main hero assassin/mage, jangan pakai hero tank.",
    subtotal: 150000,
    discount: 15000,
    fee: 2500,
    total: 137500,
    etaMinutes: 720,
    progressPercent: 85,
    status: "ON_PROGRESS",
    paymentMethod: "XENDIT_QRIS",
    workerCommission: 105000,
    createdAt: "2025-05-10T08:00:00Z",
  },
  {
    id: "jki-2",
    invoiceId: "TUG-JKI-2025-000098",
    userId: "u-1",
    userName: "Rizky Aditya Pratama",
    userPhone: "0812-3456-7890",
    gameId: "g-val",
    gameName: "Valorant",
    workerId: "w-2",
    workerName: 'Sarah "Valkyrie"',
    startTierName: "Silver 3",
    targetTierName: "Gold 3",
    currentTierName: "Gold 3",
    accountEmail: "rizky.riot@gmail.com",
    notes: "Main Reyna / Jett di server Jakarta.",
    subtotal: 180000,
    discount: 0,
    fee: 2500,
    total: 182500,
    etaMinutes: 960,
    progressPercent: 100,
    status: "COMPLETED",
    paymentMethod: "XENDIT_VA",
    workerCommission: 135000,
    createdAt: "2025-05-07T12:00:00Z",
  },
];

export const DUMMY_VOUCHERS: VoucherItem[] = [
  {
    id: "v-1",
    code: "HEMAT20",
    type: "PERCENT",
    value: 20,
    maxDiscount: 50000,
    minSpend: 30000,
    quotaTotal: 500,
    quotaUsed: 312,
    scope: "ALL",
    validFrom: "2025-01-01T00:00:00Z",
    validUntil: "2028-12-31T23:59:59Z",
    isActive: true,
  },
  {
    id: "v-2",
    code: "NEWUSER5K",
    type: "FIXED",
    value: 5000,
    minSpend: 20000,
    quotaTotal: 1000,
    quotaUsed: 654,
    scope: "ALL",
    validFrom: "2025-01-01T00:00:00Z",
    validUntil: "2028-12-31T23:59:59Z",
    isActive: true,
  },
  {
    id: "v-3",
    code: "JOKIKILAT15",
    type: "PERCENT",
    value: 15,
    maxDiscount: 35000,
    minSpend: 100000,
    quotaTotal: 200,
    quotaUsed: 78,
    scope: "JOKI",
    validFrom: "2025-01-01T00:00:00Z",
    validUntil: "2028-12-31T23:59:59Z",
    isActive: true,
  },
];

export const DUMMY_TESTIMONIALS = [
  {
    id: "t-1",
    name: "Rizky Aditya Pratama",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=60",
    game: "Mobile Legends",
    comment:
      "Top up ML 172 diamond jam 22.00, jam 22.01 diamond langsung masuk. Ngeri banget cepetnya! Langsung bisa gacha skin idaman.",
    rating: 5,
    date: "1 hari yang lalu",
  },
  {
    id: "t-2",
    name: "Sarah Permata",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=60",
    game: "Valorant Joki Rank",
    comment:
      "Joki Mythic-nya rapi parah, dikasih screenshot tiap selesai match. Akun aman dan joki ramah banget diajak diskusi.",
    rating: 5,
    date: "3 hari yang lalu",
  },
  {
    id: "t-3",
    name: "Bagas Nugraha",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=60",
    game: "Free Fire",
    comment:
      "Harganya paling murah se-Indonesia dibanding toko lain, ada promo voucher HEMAT20 lagi. Sudah langganan 5 kali tanpa kendala.",
    rating: 5,
    date: "5 hari yang lalu",
  },
];

export const DUMMY_BLOG_POSTS = [
  {
    id: "b-1",
    slug: "tips-cepat-naik-mythic-glory-season-ini",
    title: "5 Tips Efektif Push Rank Solo ke Mythic Glory Season Ini",
    excerpt:
      "Kuasai hero meta terkini, pahami makro rotasi jungle, dan optimalkan timing emblem untuk menembus Mythic Glory tanpa frustrasi.",
    category: "Tips & Trik",
    readTime: "4 menit baca",
    publishedAt: "8 Mei 2025",
    author: "Tim Editorial TopUpGame",
    coverUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=70",
    content: `
Menembus rank Mythic Glory bukan sekadar soal mekanik jari, melainkan pemahaman makro gameplay dan kontrol mental saat solo queue.

### 1. Batasi Hero Pool Anda ke Maksimal 3 Hero Meta
Fokus mendalami 2-3 hero yang sedang kuat di patch terbaru. Dengan begitu, Anda lebih peka membaca posisi musuh di minimap daripada memikirkan urutan skill.

### 2. Prioritaskan Objektif: Turtle & Lord di Atas Kills
Kills yang banyak tidak menjamin kemenangan jika turret tidak terdorong. Jadikan eliminasi lawan sebagai momentum untuk mengamankan Turtle atau menara luar.

### 3. Jaga Komunikasi & Jangan Terpancing Emosi
Jika tim Anda tertinggal di early game, mainkan strategi defensif dan tunggu blunder lawan di area high ground base.
    `,
  },
  {
    id: "b-2",
    slug: "bocoran-event-diamond-kuning-mlbb-2025",
    title: "Bocoran Jadwal & Cara Maksimalkan Event Promo Diamond Kuning 2025",
    excerpt:
      "Semua yang perlu kamu ketahui tentang event diamond kuning tahun ini agar bisa beli skin Epic seharga 1 diamond asli!",
    category: "Berita Game",
    readTime: "3 menit baca",
    publishedAt: "5 Mei 2025",
    author: "ViperML",
    coverUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=70",
    content: `
Event Promo Diamond Kuning selalu menjadi ajang berburu skin paling dinanti para player Mobile Legends. 

Pastikan Anda telah menyiapkan diamond dasar dengan melakukan top-up paket Weekly Diamond Pass jauh hari sebelumnya agar saat promo berlangsung tinggal checkout skin impian Anda dengan harga 1 Diamond!
    `,
  },
];

export const DUMMY_FAQS = [
  {
    category: "Top-Up & Diamond",
    question: "Berapa lama proses diamond masuk setelah pembayaran?",
    answer:
      "Rata-rata pemrosesan top-up otomatis memakan waktu kurang dari 60 detik setelah pembayaran terverifikasi oleh payment gateway kami.",
  },
  {
    category: "Top-Up & Diamond",
    question: "Bagaimana jika User ID atau Zone ID yang saya masukkan salah?",
    answer:
      "Sistem kami melakukan pengecekan nickname otomatis. Jika User ID tidak terdaftar, order akan otomatis ditahan dan dana Anda aman untuk diperbaiki melalui Customer Service.",
  },
  {
    category: "Layanan Joki Rank",
    question: "Apakah akun saya aman selama proses joki rank?",
    answer:
      "100% aman dan bergaransi. Akun Anda ditangani oleh pro-player bersertifikasi, data login dienkripsi dengan standar militer AES-256-GCM, dan joki dilarang keras membuka chat pribadi atau menggunakan diamond/item akun Anda.",
  },
  {
    category: "Layanan Joki Rank",
    question: "Bisakah saya memantau progres kenaikan rank dan chat dengan joki?",
    answer:
      "Tentu saja! Anda dapat memantau persentase bintang realtime dan berkomunikasi langsung melalui fitur Chat Joki di dashboard pesanan Anda.",
  },
  {
    category: "Pembayaran & Garansi",
    question: "Metode pembayaran apa saja yang didukung?",
    answer:
      "Kami mendukung QRIS (semua e-wallet dan m-banking), Virtual Account (BCA, Mandiri, BRI, BNI), DANA, GoPay, OVO, ShopeePay, serta Transfer Manual Bank BCA.",
  },
  {
    category: "Pembayaran & Garansi",
    question: "Bagaimana jika pesanan saya gagal terkirim?",
    answer:
      "Jika terjadi gangguan server supplier setelah 3 kali percobaan ulang, saldo Anda akan direfund 100% atau diproses ulang secara instan oleh admin.",
  },
];

export const DUMMY_ADMIN_METRICS = {
  todayRevenue: 14850000,
  yesterdayRevenue: 12400000,
  monthlyRevenue: 342500000,
  totalOrdersToday: 384,
  activeJokiOrders: 18,
  pendingManualPayments: 4,
  lowStockAlerts: 2,
};

export const DUMMY_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: "aud-1",
    actorName: "Bagas Nugroho",
    actorRole: "admin",
    action: "UPDATE",
    entityType: "product_price",
    entityId: "p-ml-172",
    referenceCode: "ML-172-DM",
    beforeData: { priceSell: 41000, margin: 4500 },
    afterData: { priceSell: 43000, margin: 6500 },
    ipAddress: "182.1.22.45",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    createdAt: "2025-05-10T11:20:00Z",
  },
  {
    id: "aud-2",
    actorName: "Sistem Xendit Webhook",
    actorRole: "super_admin",
    action: "UPDATE",
    entityType: "order_topup",
    entityId: "ord-1",
    referenceCode: "TUG-2025-000431",
    beforeData: { status: "PENDING_PAYMENT" },
    afterData: { status: "SUCCESS", paidAt: "2025-05-10T14:02:15Z" },
    ipAddress: "52.76.120.18",
    createdAt: "2025-05-10T14:02:16Z",
  },
  {
    id: "aud-3",
    actorName: 'Andika "ViperML"',
    actorRole: "joki",
    action: "UPDATE",
    entityType: "order_joki",
    entityId: "jki-1",
    referenceCode: "TUG-JKI-2025-000112",
    beforeData: { progressPercent: 60, currentTierName: "Legend II (2 Bintang)" },
    afterData: { progressPercent: 85, currentTierName: "Legend I (4 Bintang)" },
    ipAddress: "114.124.201.88",
    createdAt: "2025-05-10T13:45:00Z",
  },
  {
    id: "aud-4",
    actorName: "Dwi Kartika Sari",
    actorRole: "super_admin",
    action: "READ_SENSITIVE",
    entityType: "order_joki_credentials",
    entityId: "jki-1",
    referenceCode: "TUG-JKI-2025-000112",
    beforeData: {},
    afterData: { note: "Buka kredensial login terenkripsi untuk investigasi bug OTP" },
    ipAddress: "180.252.160.9",
    createdAt: "2025-05-10T09:15:00Z",
  },
];
